language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run pylint api/api
  - pipenv run pylint api/tests
  - pipenv run pytest
branches:
  only:
    - master
